wandb_version: 1

FLOPs:
  desc: null
  value: 1507755400.0
Parameters:
  desc: null
  value: 13004888
_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1651234227
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 1
      4: 3.8.10
      5: 0.12.15
      8:
      - 5
batch_size:
  desc: null
  value: 256
classes:
  desc: null
  value: 1000
data:
  desc: null
  value: /mnt/e/ImageNet-Downsampled/data
dataset:
  desc: null
  value: SmallImageNet
depth:
  desc: null
  value: 50
dryrun:
  desc: null
  value: null
epochs:
  desc: null
  value: 100
evaluate:
  desc: null
  value: false
log_freq:
  desc: null
  value: 500
lr:
  desc: null
  value: 0.1
model_type:
  desc: null
  value: imagenet
momentum:
  desc: null
  value: 0.9
ngpu:
  desc: null
  value: 1
prefix:
  desc: null
  value: test
print_freq:
  desc: null
  value: 100
project:
  desc: null
  value: Imagenet
resume:
  desc: null
  value: ''
seed:
  desc: null
  value: 1234
size:
  desc: null
  value: 8
start_epoch:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0001
workers:
  desc: null
  value: 4
